---
title: "Tech Jobs & Unemployment"
author: "Zoe Meers"
format: html
---

```{r}
library(strayr)
library(readabs)
library(fuzzyjoin)
```


```{r}
anzsco_aced_gos <- read.csv('anzsco-aced.csv') |>
    mutate(aced_foe_narrow_code = as.character(ifelse(nchar(aced_foe_narrow_code)==3, paste0(0, aced_foe_narrow_code), aced_foe_narrow_code)))

dese_completion_rates_by_broad_foe <- read.csv('dese-foe-completion-numbers.csv') |>
    janitor::clean_names() |>
    mutate(sum_of_completions = as.numeric(gsub(",", "", sum_of_completions)), year = as.numeric(year))

anzsco_aced_gos <- anzsco_aced_gos |>
    left_join(dese_completion_rates_by_broad_foe, by = c("aced_foe_broad" = "broad_field_of_education_primary"), relationship = "many-to-many") |>
    mutate(gos_code = gsub(" \\+ ", " and ", gos_code))
```

```{r}
tech_job_codes <- c('1350 ICT Managers nfd',	 '1351 ICT Managers',  '2232 ICT Trainers',  '2247 Management and Organisation Analysts', '2249 Other Information and Organisation Professionals',	 '2252 ICT Sales Professionals',  '2324 Graphic and Web Designers, and Illustrators',  '2334 Electronics Engineers',  '2600 ICT Professionals nfd',  '2610 Business and Systems Analysts, and Programmers nfd',  '2611 ICT Business and Systems Analysts',  '2612 Multimedia Specialists and Web Developers',  '2613 Software and Applications Programmers',  '2620 Database and Systems Administrators, and ICT Security Specialists nfd',	 '2621 Database and Systems Administrators, and ICT Security Specialists',	 '2630 ICT Network and Support Professionals nfd',  '2631 Computer Network Professionals', 	 '2632 ICT Support and Test Engineers',  '2633 Telecommunications Engineering Professionals',  '3100 Engineering, ICT and Science Technicians nfd',  '3124 Electronic Engineering Draftspersons and Technicians',  '3130 ICT and Telecommunications Technicians nfd',  '3131 ICT Support Technicians',  '3132 Telecommunications Technical Specialists',  '3424 Telecommunications Trades Workers')

clean_eq08 <- read_lfs_datacube("EQ08") |> 
    mutate(tech_occupation = case_when(
        occupation_of_main_job__anzsco_2013_v1.2 %in% tech_job_codes ~ 'Tech',
        TRUE ~ 'Not tech'
    )) |>
    separate(col = occupation_of_main_job__anzsco_2013_v1.2, into = c("anzsco_unit_code", "anzsco_unit"), sep = " ", extra = "merge") |>
    group_by(date, anzsco_unit_code, anzsco_unit, tech_occupation) |>
    summarise(employed_total_000 = sum(employed_total_000), number_of_hours_actually_worked_in_all_jobs_000_hours = sum(number_of_hours_actually_worked_in_all_jobs_000_hours)) |>
    ungroup()
```

```{r}
clean_eq08_tech_eng_roles <- clean_eq08 |> 
    filter(anzsco_unit_code %in% c(2613, 2611, 2621)) |> 
    mutate(year = lubridate::year(as.Date(date))) |>
    filter(year > 2017) |>
    mutate(anzsco_unit_code = as.integer(anzsco_unit_code)) |>
    left_join(anzsco_aced_gos |> filter(aced_foe_broad == "Information Technology"), by = c("anzsco_unit_code" = "anzsco_unit_code", "year" = "year", "anzsco_unit" = "anzsco_unit")) |>
    filter(year < 2024) |>
    rename(tertiary_graduates = sum_of_completions)
```

```{r}
graduate_outcome_survey_2019 = read_excel("2019_gos_survey.xlsx", sheet = "Table2", skip = 1) |>
    rename(foe = `...1`) |>
    janitor::clean_names() |>
    select(foe, starts_with("full")) |>
    slice(c(1:22))
graduate_outcome_survey_2021 = read_excel("2021_gos_survey.xlsx", sheet = "EMP_UG_ALL_2Y_AREA", skip = 1) |>
    rename(foe = `...1`) |>
    janitor::clean_names() |>
    select(foe, starts_with("full")) |>
    slice(c(1:22))
graduate_outcome_survey_2023 = read_excel("2023_gos_survey.xlsx", sheet = "EMP_UG_ALL_2Y_AREA", skip = 1) |>
    rename(foe = `...1`) |>
    janitor::clean_names() |>
    select(foe, starts_with("full")) |>
    slice(c(1:22)) |>
    mutate(full_time_employment_2022 = as.double(full_time_employment_2022), full_time_employment_2023 = as.double(full_time_employment_2023))

graduate_outcome_survey <- graduate_outcome_survey_2019 |>
    left_join(graduate_outcome_survey_2021, by = c("foe" = "foe")) |>
    left_join(graduate_outcome_survey_2023, by = c("foe" = "foe")) |>
    pivot_longer(-foe, values_to = "fte_percent", names_to = "year") |>
    mutate(year = as.numeric(gsub("full_time_employment_", "", year)))

ggplot(graduate_outcome_survey |> 
    filter(foe %in% c("All", "Computing and Information Systems", "Science and mathematics")), 
    aes(year, fte_percent/100, color = foe)) + 
    geom_point() + 
    geom_line() +
    theme_tca() + 
    ylim(c(0,1)) + 
    labs(color = "Broad Field of Education", y = "Tertiary Grads in FTE within 3 months", x = "") +
    scale_y_continuous(labels = scales::percent) +
    theme(legend.direction = 'vertical')

ggsave(last_plot(), filename = "fte_workers.png")
```

```{r}
clean_eq08_tech_eng_roles_grad <- clean_eq08_tech_eng_roles |>
    left_join(graduate_outcome_survey, by = c("year" = "year", "gos_code" = "foe")) |>
    group_by(year, gos_code, fte_percent, tertiary_graduates) |>
    summarise(employed_total = sum(employed_total_000)*1E3) |>
    ungroup() |>
    mutate(
        number_of_new_grads_fte = tertiary_graduates*(fte_percent/100), 
        new_grads_workforce = (number_of_new_grads_fte/employed_total)*100
    )

ggplot(clean_eq08_tech_eng_roles_grad, aes(year, new_grads_workforce/100, color = gos_code)) + 
    geom_point() + 
    geom_line() + 
    theme_tca() +
    theme_tca() + 
    ylim(c(0,1)) + 
    labs(color = "Broad Field of Education", y = "CS grads in FTE tech roles within 3 months", x = "",
    title = "CS grads in FTE tech roles within 3 months\nof graduation") +
    scale_y_continuous(labels = scales::percent) +
    theme(legend.direction = 'vertical')

ggsave(last_plot(), filename = "new_grad_fte_prop.png")
```

```{r}
current_swe_labour_force <- read_excel("~/downloads/Current job - SWE.xlsx", skip = 8, n_max = 88) |>
    select(c(1,2)) |>
    rename(employment_no = `...2`, date = `Survey month`) |>
    filter(employment_no != 0.0) |>
    mutate(employment_no = employment_no * 1000)

current_swe_20_24_labour_force <- read_excel("~/downloads/Current SWE - 20-24yo.xlsx", skip = 11, n_max = 88) |>
    select(c(1,2)) |>
    rename(age_20_24_employment_no = `...2`, date = `Survey month`) |>
    filter(age_20_24_employment_no != 0.0) |>
    mutate(age_20_24_employment_no = age_20_24_employment_no * 1000)

former_swe_labour_force <- read_excel("~/downloads/Last job - SWE.xlsx", skip = 10, n_max = 86) |>
    select(c(1,3)) |>
    rename(unemployment_no = `...3`, date = `Survey month`) |>
    filter(unemployment_no != 0.0) |>
    mutate(unemployment_no = unemployment_no * 1000)

swe_labour_force <- current_swe_labour_force |>
    left_join(former_swe_labour_force, by = c("date" = "date")) |>
    left_join(current_swe_20_24_labour_force, by = c("date" = "date")) |>
    mutate(total_labour_force = employment_no + unemployment_no, date = as.Date(paste0("01-", date), format = "%d-%b-%y")) |>
    mutate(smoothed_total_labour_force = zoo::rollmean(total_labour_force, k = 4, align = "right", fill = NA),
        smoothed_employed = zoo::rollmean(employment_no, k = 4, align = "right", fill = NA),
        smoothed_unemployed = zoo::rollmean(unemployment_no, k = 4, align = "right", fill = NA),
        smoothed_20_24_employed = zoo::rollmean(age_20_24_employment_no, k = 4, align = "right", fill = NA)
        )


p1 <- ggplot(swe_labour_force) +
    geom_line(aes(date, smoothed_total_labour_force, color = 'Total SWEs')) +
    geom_line(aes(date, smoothed_employed, color = 'Number of employed SWEs')) +
    geom_line(aes(date, smoothed_20_24_employed, color = 'Number of entry-level SWEs (aged 20-24)')) +
    theme_tca() +
    scale_color_manual(
        values = custom_colors[c(1, 3, 4)],
        drop = FALSE 
    ) + 
    geom_vline(xintercept = as.Date("2020-03-01"), linetype = "dashed", color = custom_colors[c(2)], size = 0.5) +
  annotate("text", x = as.Date("2020-03-01"), y = max(na.omit(swe_labour_force$smoothed_total_labour_force)), label = "COVID onset", vjust = 1.2, angle = 90, hjust = 1, color = "grey") +
    labs(colour = '', y = 'Number of persons', x = '', subtitle = 'SWE Labour Force in Australia', caption = ' ') + 
    scale_y_continuous(labels = scales::comma)

p2 <- ggplot(swe_labour_force) +
    geom_line(aes(date, smoothed_unemployed), color = "#000000") +
    theme_tca() +
    geom_vline(xintercept = as.Date("2020-03-01"), linetype = "dashed", color = custom_colors[c(2)], size = 0.5) +
  annotate("text", x = as.Date("2020-03-01"), y = max(na.omit(swe_labour_force$smoothed_unemployed)), label = "COVID onset", vjust = 1.2, angle = 90, hjust = 1, color = "grey") +
    labs(subtitle = 'Number of unemployed SWEs', y = '', x = '', caption = 'Quarterly rolling average smoothed on annual period.') + 
    scale_y_continuous(labels = scales::comma)

combined <- p1 + p2

ggsave(combined, filename = "SWE_labour_force.png", width = 12)
```